name: SanKhach
options:
  minimumXcodeGenVersion: 2.41.0
targets:
  SanKhach:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: vn.sankhach.smartcity
        PRODUCT_NAME: SanKhach
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: 1
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: Săn Khách
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
